### ISSUE TITLE
How can I create a bi-directional pipe between two Netcat clients?

### ISSUE THREAD

**Issue by cognifloyd** [rhelmot/nclib#4]
I'm trying to replace the following TCP to UDP converter with something based on nclib.
The problem with it is that it can only accept one TCP client at a time.
```
fifo='/tmp/tcp_proxy_fifo'
mkfifo $fifo
ncat -k -l 61111 < $fifo | ncat -u 127.0.0.1 62222 > $fifo
```

So far, I've got something like this:
```
    tcp_server = TCPServer(src)
    for tcp_client in tcp_server:
        print('Accepted client %s:%d' % tcp_client.peer)
        udp_client = Netcat(dest, udp=True)
        while True:
            udp_client.send(tcp_client.recv())
            tcp_client.send(udp_client.recv())
```

Is there a way to bind the two clients to each other so that everything sent by one is received by the other until the either client disconnects?

_Aargh. I submitted this too soon. I can never remember which editor uses Ctrl+Enter, and which uses just a plain enter. Edited to finish my question._

**Comment by rhelmot** [comment]
You could do some magic with dup/dup2, but I think if you want to translate between tcp and udp the only way to do it is to manually receive and send each packet - the translation has to happen in user code.

In order to make this work you'll want to use threads. I don't remember the python threading API exactly off the top of my head, but something like this:

```python
import threading

class TranslateThread(threading.Thread):
  def __init__(self, nc_src, nc_dest):
    self.nc_src = nc_src
    self.nc_dst = nc_dst

  def run(self):
    while True: # or possibly a termination condition
      self.nc_dst.send(self.nc_src.recv())

tcp_server = TCPServer(src)
for tcp_client in tcp_server:
  print('Accepted client %s:%d' % tcp_client.peer)
  udp_client = Netcat(dest, udp=True)
  TranslateThread(udp_client, tcp_client).start()
  TranslateThread(tcp_client, udp_client).start()
```

This is more or less how you'd have to do this if writing C as well. As usual with threaded programs, resource management and termination conditions are going to be a pain...

**Comment by rhelmot** [comment]
You could also do some magic with select (there's a nclib wrapper for select that makes it work with Netcat objects) but that's much more complicated :)

**Comment by cognifloyd** [comment]
I like the idea of TranslateThread - that would reduce some of the duplication in what I just worked out.

This seems to work fairly well (but it depends on eventlet): https://gist.github.com/cognifloyd/42198f1d4eaecc889309f2009187fed5
